/* TRIGGER REGISTRA INSERT */

CREATE TABLE
    historial_cliente_insert(
        id INT,
        nombre VARCHAR(45),
        fecha DATE,
        usuario VARCHAR(45)
    );

CREATE TRIGGER INSERT_CLIENTE_AI AFTER INSERT ON CLIENTES 
FOR EACH ROW INSERT INTO HISTORIAL_CLIENTE_INSERT(
ID, NOMBRE, FECHA, USUARIO) VALUES(NEW.ID, NEW.NOMBRE
, CURDATE(), CURRENT_USER()) ; INSERT INTO CLIENTES
(ID, NOMBRE, APELLIDO, EMAIL, TELEFONO, ID_NACIONALIDAD
) VALUES(121, 'CAROLINA', 'MURILLO', 'ALJFD', 2783459
, 3) ; /* TRIGGER ACTUALIZACION */ 
CREATE TABLE HISTORIAL_CLIENTE_UPDATE(ID INT, NOMBRE_NUEVO 
VARCHAR(45), NOMBRE_ANTIGUO VARCHAR(45), APELLIDO_NUEVO 
VARCHAR(45), APELLIDO_ANTIGUO VARCHAR(45), EMAIL_NUEVO 
VARCHAR(45), EMAIL_ANTIGUO VARCHAR(45), TELEFONO_NUEVO 
VARCHAR(45), TELEFONO_ANTIGUO VARCHAR(45), FECHA DATE
, USUARIO VARCHAR(45)) ; CREATE TRIGGER UPDATE_CLIENTES_BU 
BEFORE UPDATE ON CLIENTES FOR EACH ROW INSERT INTO 
HISTORIAL_CLIENTE_UPDATE(ID, NOMBRE_NUEVO, NOMBRE_ANTIGUO
, APELLIDO_NUEVO, APELLIDO_ANTIGUO, EMAIL_NUEVO, EMAIL_ANTIGUO
, TELEFONO_NUEVO, TELEFONO_ANTIGUO, FECHA, USUARIO
) VALUES(NEW.ID, NEW.NOMBRE, OLD.NOMBRE, NEW.APELLIDO
, OLD.APELLIDO, NEW.EMAIL, OLD.EMAIL, NEW.TELEFONO
, OLD.TELEFONO, CURDATE(), CURRENT_USER()) ; UPDATE 
CLIENTES SET EMAIL ='ASHFDI' 
	, telefono=12121212122 WHERE id=121;
